apiVersion: v1
kind: Service 
metadata:
  name: mysql 
spec:
  selector: #how service is going to map with mysql deployment
    app: mysql
  ports:
    - port: 3306
  clusterIP: None #this menas we are going to use the Pod IP to communicate. 